# Generated by Django 6.0.3 on 2026-03-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50, unique=True)),
                ('room_type', models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Lab')], max_length=20)),
                ('camera_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
