# Generated by Django 6.0.3 on 2026-03-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_add_class_id_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
