# Generated by Django 6.0.3 on 2026-03-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=100)),
                ('slot_type', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=20)),
                ('slot', models.CharField(max_length=10)),
                ('classroom', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('day', 'slot', 'classroom')},
            },
        ),
    ]
